### PR TITLE
Changes to units processing

### PR DESCRIPTION
**Pull request by ehwenk**
* add functionality to read in units from a column (issue #7)
* make it possible to have unit conversions for values that are bins/ranges  (issue #10)
* fix warnings during unit conversions (issue #65)
* split function `process_flag_unsupported_values`, so that `unsupported characters` and `does not convert to numeric` errors are assigned before unit conversions and `value out of range` errors are assigned after unit conversions

### CODE REVIEW

**Comment by yangsophieee** [comment]
I still need to add tests for this and fix a few tests that are currently failing.

**Comment by ehwenk** [comment]
> I still need to add tests for this and fix a few tests that are currently failing.

I think there is a bigger issue with these changes that I hadn't appreciated that is one of the reason tests are failing - now that units are read in during `dataset_process` rather than `dataset_config` the entire remake file isn't really accurate and although AusTraits builds fine with the empty units_conversions_functions argument, it seems the tests are complaining.

**Comment by ehwenk** [comment]
@dfalster As part of allowing units to be read in from a column instead of just from metadata[["traits"]], the unit conversions file is now required for `dataset_process` instead of `dataset_config`. I've currently shortcut the way the units conversions file was being sources through the remake file, but this should be changed.
- need to remove unit conversions from `dataset_config` - both in the function and in how the remake file is constructed
- need to add unit conversions from `dataset_process` - both in the function and in how the remake file is constructed
- delete line 86 in process.R (currently commented out)
- change line 115 in process.R to reflect change; that is where unit conversions are currently being sourced.

I think I know how to change the building of the remake file, but also a little worried about trying it - and thinking maybe this should wait until austraits.build swaps to traits.build package.

**Review by dfalster — APPROVED** [review]
Nice work!

I've simplified the unit conversions for bins and ranges. Can you please check it works on austraits.build?

**Pull request merged**
