### PR TITLE
More version info on build

### PR DESCRIPTION
**Pull request by dfalster**
This PR addresses two issues

1. Ensure call for SHA works when not in a git repo
2. embed traits.build version in database config/metadata.yml (#124)

### CODE REVIEW

**Comment by dfalster** [comment]
@ehwenk - I added above features. Can you review what to call the version thing? 

@yangsophieee - can you add appropriate tests for above changes?

**Review by ehwenk — COMMENTED** [review]
I think the best option is some combination of `resource_type = software` and `compiled by`. For instance, the current line from the Zenodo reference, under related identifiers is:
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="URL" relationType="IsCompiledBy" resourceTypeGeneral="Dataset">https://github.com/traitecoevo/austraits.build/tree/v4.2.0</relatedIdentifier>

Which, for the next release will become
resourceTypeGeneral="Software" and list the traits.build values

This also explains with how I chose to map it into the metadata.yml file 
```
  - related_identifier_type: url 
    identifier: https://github.com/traitecoevo/austraits.build/tree/v4.2.0
    relation_type: isCompiledBy
    resource_type: dataset
```
which should be:
```
  - related_identifier_type: url 
    identifier: https://github.com/traitecoevo/traits.build
    relation_type: isCompiledBy
    resource_type: software
    has_version: version
```

**Comment by yangsophieee** [comment]
@dfalster I've added tests, please check if they're what you envisioned. Thanks!

**Comment by dfalster** [comment]
@ehwenk so is that how you want it in austraits$metadata? so it would look like

title: 'AusTraits: a curated plant trait database for the Australian flora'
description: AusTraits is a transformative database, containing measurements on the
  traits of Australia's plant taxa, standardised from hundreds of disconnected primary
  sources. While this repository contains the harmonised data, the raw data and code
  used to build the resource are also available on the project's GitHub repository,http://traitecoevo.github.io/austraits.build.
  Further information on the project is available in the associated publication and
  at the project website https://austraits.org.
version: 4.2.0.9000
doi: 10.5281/zenodo.3568417
structure_URI: https://github.com/traitecoevo/austraits.build
geo_location:
  geo_location_place: Australia
  geodetic_datum: EPSG:4326
language: en
related_identifiers:
- related_identifier_type: url 
  identifier: https://github.com/traitecoevo/traits.build
  relation_type: isCompiledBy
  resource_type: software
  has_version: 0.9.0
- related_identifier_type: url
  identifier: https://github.com/traitecoevo/austraits.build/tree/v4.2.0
  relation_type: isCompiledBy
  resource_type: dataset
  ```
  ```

**Comment by ehwenk** [comment]
That is how the information is presented on Zenodo and my interpretation of what the DataCite standards are. I think it is best if we keep to that, since the intent of this file was, in part, that the information can possibly be automatically harvested by Zenodo in the future.

**Review by ehwenk — APPROVED** [review]
Looks good - just confirmed the few queries I had

**Pull request merged**
